/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;

/**
 *
 * @author alberto
 */
public class BajaActividad extends javax.swing.JDialog {

    /**
     * Creates new form BajaActividad
     */
    public BajaActividad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotonDarDeBaja = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableActividades = new javax.swing.JTable();
        BotonCancelarBaja = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Seleccionar Actividad");

        BotonDarDeBaja.setBackground(new java.awt.Color(255, 51, 51));
        BotonDarDeBaja.setForeground(new java.awt.Color(255, 255, 255));
        BotonDarDeBaja.setText("Dar de baja");
        BotonDarDeBaja.setActionCommand("DarDeBaja");
        BotonDarDeBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonDarDeBajaActionPerformed(evt);
            }
        });

        jTableActividades.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jTableActividades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableActividades);

        BotonCancelarBaja.setText("Cancelar");
        BotonCancelarBaja.setActionCommand("CancelarDarDeBaja");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BotonDarDeBaja)
                        .addGap(18, 18, 18)
                        .addComponent(BotonCancelarBaja)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonDarDeBaja)
                    .addComponent(BotonCancelarBaja))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonDarDeBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonDarDeBajaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonDarDeBajaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BotonCancelarBaja;
    public javax.swing.JButton BotonDarDeBaja;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTableActividades;
    // End of variables declaration//GEN-END:variables
}
