/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 *
 * @author alber
 */
public class VistaSocios extends javax.swing.JPanel {

    /**
     * Creates new form VistaSocios
     */
    public VistaSocios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTableSocios = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        BotonNuevoSocio = new javax.swing.JButton();
        BotonBajaSocio = new javax.swing.JButton();
        BotonActuSocio = new javax.swing.JButton();
        ComboBuscar = new javax.swing.JComboBox<>();
        CampoBuscar = new javax.swing.JTextField();
        BotonBuscar = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(949, 380));

        jTableSocios.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jTableSocios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableSocios);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("Gestión de Socios");

        BotonNuevoSocio.setBackground(new java.awt.Color(102, 102, 102));
        BotonNuevoSocio.setForeground(new java.awt.Color(255, 255, 255));
        BotonNuevoSocio.setText("Nuevo Socio");
        BotonNuevoSocio.setActionCommand("NuevoSocio");

        BotonBajaSocio.setBackground(new java.awt.Color(102, 102, 102));
        BotonBajaSocio.setForeground(new java.awt.Color(255, 255, 255));
        BotonBajaSocio.setText("Baja de Socio");
        BotonBajaSocio.setActionCommand("BajaSocio");

        BotonActuSocio.setBackground(new java.awt.Color(102, 102, 102));
        BotonActuSocio.setForeground(new java.awt.Color(255, 255, 255));
        BotonActuSocio.setText("Actualización de Socio");
        BotonActuSocio.setActionCommand("ActualizacionSocio");

        ComboBuscar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DNI", "Nombre", "Categoria" }));

        CampoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoBuscarActionPerformed(evt);
            }
        });

        BotonBuscar.setText("🔎");
        BotonBuscar.setActionCommand("BuscarSocio");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 937, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BotonNuevoSocio)
                                .addGap(18, 18, 18)
                                .addComponent(BotonBajaSocio)
                                .addGap(18, 18, 18)
                                .addComponent(BotonActuSocio)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ComboBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CampoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ComboBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CampoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonBuscar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonNuevoSocio)
                    .addComponent(BotonBajaSocio)
                    .addComponent(BotonActuSocio))
                .addContainerGap(53, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CampoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BotonActuSocio;
    public javax.swing.JButton BotonBajaSocio;
    public javax.swing.JButton BotonBuscar;
    public javax.swing.JButton BotonNuevoSocio;
    public javax.swing.JTextField CampoBuscar;
    public javax.swing.JComboBox<String> ComboBuscar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable jTableSocios;
    // End of variables declaration//GEN-END:variables
}
