/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 *
 * @author alber
 */
public class VistaMonitores extends javax.swing.JPanel {

    /**
     * Creates new form VistaMonitores
     */
    public VistaMonitores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMonitores = new javax.swing.JTable();
        BotonNuevoMonitor = new javax.swing.JButton();
        BotonBajaMonitor = new javax.swing.JButton();
        BotonActuMonitor = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(949, 380));

        jTableMonitores.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jTableMonitores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableMonitores);

        BotonNuevoMonitor.setBackground(new java.awt.Color(102, 102, 102));
        BotonNuevoMonitor.setForeground(new java.awt.Color(255, 255, 255));
        BotonNuevoMonitor.setText("Nuevo Monitor");
        BotonNuevoMonitor.setActionCommand("NuevoMonitor");

        BotonBajaMonitor.setBackground(new java.awt.Color(102, 102, 102));
        BotonBajaMonitor.setForeground(new java.awt.Color(255, 255, 255));
        BotonBajaMonitor.setText("Baja de Monitor");
        BotonBajaMonitor.setActionCommand("BajaMonitor");

        BotonActuMonitor.setBackground(new java.awt.Color(102, 102, 102));
        BotonActuMonitor.setForeground(new java.awt.Color(255, 255, 255));
        BotonActuMonitor.setText("Actualización de Monitor");
        BotonActuMonitor.setActionCommand("ActualizacionMonitor");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Gestión de Monitores");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 819, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BotonNuevoMonitor)
                                .addGap(18, 18, 18)
                                .addComponent(BotonBajaMonitor)
                                .addGap(18, 18, 18)
                                .addComponent(BotonActuMonitor)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonNuevoMonitor)
                    .addComponent(BotonBajaMonitor)
                    .addComponent(BotonActuMonitor))
                .addContainerGap(101, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BotonActuMonitor;
    public javax.swing.JButton BotonBajaMonitor;
    public javax.swing.JButton BotonNuevoMonitor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTableMonitores;
    // End of variables declaration//GEN-END:variables
}
