/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author Antón
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        portada = new javax.swing.JMenu();
        pPrincipal = new javax.swing.JMenuItem();
        Monitores = new javax.swing.JMenu();
        gestionMonitores = new javax.swing.JMenuItem();
        Socios = new javax.swing.JMenu();
        gestionSocios = new javax.swing.JMenuItem();
        Actividades = new javax.swing.JMenu();
        gestionActividades = new javax.swing.JMenuItem();
        Salir = new javax.swing.JMenu();
        salirAplicacion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        portada.setText("Portada");

        pPrincipal.setText("Pantalla principal");
        pPrincipal.setActionCommand("PantallaPrincipal");
        portada.add(pPrincipal);

        jMenuBar2.add(portada);

        Monitores.setText("Monitores");

        gestionMonitores.setText("Gestión de Monitores");
        gestionMonitores.setActionCommand("GestionMonitores");
        Monitores.add(gestionMonitores);

        jMenuBar2.add(Monitores);

        Socios.setText("Socios");

        gestionSocios.setText("Gestión de Socios");
        gestionSocios.setActionCommand("GestionSocios");
        Socios.add(gestionSocios);

        jMenuBar2.add(Socios);

        Actividades.setText("Actividades");

        gestionActividades.setText("Gestión de Actividades");
        gestionActividades.setActionCommand("GestionActividades");
        Actividades.add(gestionActividades);
        gestionActividades.getAccessibleContext().setAccessibleName("GestionActividades");

        jMenuBar2.add(Actividades);

        Salir.setText("Salir");

        salirAplicacion.setText("Salir de la aplicación");
        salirAplicacion.setActionCommand("SalirAplicacion");
        Salir.add(salirAplicacion);

        jMenuBar2.add(Salir);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 477, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenu Actividades;
    public javax.swing.JMenu Monitores;
    public javax.swing.JMenu Salir;
    public javax.swing.JMenu Socios;
    public javax.swing.JMenuItem gestionActividades;
    public javax.swing.JMenuItem gestionMonitores;
    public javax.swing.JMenuItem gestionSocios;
    private javax.swing.JMenuBar jMenuBar2;
    public javax.swing.JMenuItem pPrincipal;
    public javax.swing.JMenu portada;
    public javax.swing.JMenuItem salirAplicacion;
    // End of variables declaration//GEN-END:variables
}
