/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author alber
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
        String url =  System.getProperty("user.dir") + "\\src\\main\\resources\\images\\gimnasio.png" ;
        if(url != null) {
            Image icono = Toolkit.getDefaultToolkit().getImage(url);
            setIconImage(icono);
        }
        else{
            System.out.println("No se puede encontrar el recurso");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuPrincipal = new javax.swing.JMenuBar();
        MP_principal = new javax.swing.JMenu();
        Home = new javax.swing.JMenuItem();
        MP_monitores = new javax.swing.JMenu();
        GestionMonitores = new javax.swing.JMenuItem();
        MP_socios = new javax.swing.JMenu();
        GestionSocios = new javax.swing.JMenuItem();
        MP_actividades = new javax.swing.JMenu();
        GestionActividades = new javax.swing.JMenuItem();
        MP_salir = new javax.swing.JMenu();
        SalirAplicacion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión de Gimnasio \"Gym Nature\"");
        setPreferredSize(new java.awt.Dimension(949, 380));

        MenuPrincipal.setBackground(new java.awt.Color(255, 102, 102));
        MenuPrincipal.setForeground(new java.awt.Color(255, 255, 255));

        MP_principal.setText("🏠");
        MP_principal.setActionCommand("");
        MP_principal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MP_principalActionPerformed(evt);
            }
        });

        Home.setBackground(new java.awt.Color(204, 204, 204));
        Home.setForeground(new java.awt.Color(204, 204, 204));
        Home.setText("Home");
        MP_principal.add(Home);

        MenuPrincipal.add(MP_principal);

        MP_monitores.setForeground(new java.awt.Color(255, 255, 255));
        MP_monitores.setText("Monitores");

        GestionMonitores.setBackground(new java.awt.Color(204, 204, 204));
        GestionMonitores.setForeground(new java.awt.Color(204, 204, 204));
        GestionMonitores.setText("Gestión de Monitores");
        GestionMonitores.setActionCommand("GestionMonitores");
        GestionMonitores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestionMonitoresActionPerformed(evt);
            }
        });
        MP_monitores.add(GestionMonitores);

        MenuPrincipal.add(MP_monitores);

        MP_socios.setForeground(new java.awt.Color(255, 255, 255));
        MP_socios.setText("Socios");

        GestionSocios.setBackground(new java.awt.Color(204, 204, 204));
        GestionSocios.setForeground(new java.awt.Color(204, 204, 204));
        GestionSocios.setText("Gestión de Socios");
        GestionSocios.setActionCommand("GestionSocios");
        MP_socios.add(GestionSocios);

        MenuPrincipal.add(MP_socios);

        MP_actividades.setForeground(new java.awt.Color(255, 255, 255));
        MP_actividades.setText("Actividades");

        GestionActividades.setText("Gestión de Actividades");
        GestionActividades.setActionCommand("GestionActividades");
        MP_actividades.add(GestionActividades);

        MenuPrincipal.add(MP_actividades);

        MP_salir.setForeground(new java.awt.Color(255, 255, 255));
        MP_salir.setText("Salir");

        SalirAplicacion.setBackground(new java.awt.Color(204, 204, 204));
        SalirAplicacion.setForeground(new java.awt.Color(204, 204, 204));
        SalirAplicacion.setText("Salir de la aplicación");
        SalirAplicacion.setActionCommand("SalirAplicacion");
        MP_salir.add(SalirAplicacion);

        MenuPrincipal.add(MP_salir);

        setJMenuBar(MenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 950, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 357, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GestionMonitoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestionMonitoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GestionMonitoresActionPerformed

    private void MP_principalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MP_principalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MP_principalActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuItem GestionActividades;
    public javax.swing.JMenuItem GestionMonitores;
    public javax.swing.JMenuItem GestionSocios;
    public javax.swing.JMenuItem Home;
    public javax.swing.JMenu MP_actividades;
    public javax.swing.JMenu MP_monitores;
    public javax.swing.JMenu MP_principal;
    private javax.swing.JMenu MP_salir;
    public javax.swing.JMenu MP_socios;
    private javax.swing.JMenuBar MenuPrincipal;
    public javax.swing.JMenuItem SalirAplicacion;
    // End of variables declaration//GEN-END:variables
}
